#!/bin/bash

MAJORVER=0
MINORVER=30

DEBUGMODE=0
DIAGMODE=0

declare -a excessargs
declare -a drives
declare -a thermalzones
declare -a sensors
declare -a processes
declare -a pinghosts
declare -a traceroutes
declare -a services

excessargsCount=0
driveCount=0
zoneCount=0
sensorCount=0
processCount=0
pinghostCount=0
tracerouteCount=0
servicesCount=0

defaultThermalSensor="/sys/class/thermal/thermal_zone0/temp,1000"

temperature=""

TMPFILE="/tmp/sysmetric.tmp.${RANDOM}"
PROFILE="none"
LOGHOST="none"
GRAPHITE="none"
GRAPHITEPORT=2003
MEMINFO=0
UPTIME=0
HEARTBEAT=none
PINGCOUNT=2
PORTPING=nping
NETCATWAIT=0
NETCATTIMEOUT=2

PROGNAME=sysmetrics
REPOSITORY=https://github.com/ejohnfel/${PROGNAME}

# DebugMsg : Print Debug messages
# Parameters : [mesg]
function DebugMsg()
{
	[ ${DEBUGMODE} -gt 0 ] && echo -e "Debug : ${1}"
}

# MyVersion : Get/Set Version Info
function MyVersion()
{
	echo "Version ${sysmetricsver}"
}

# Update : Update App
# Parameters : none
function UpdateMe()
{
	pushd /tmp/ > /dev/null

	git clone ${REPOSITORY} > /dev/null 2>&1

	cd ${PROGNAME}

	current=$( md5sum "/usr/local/bin/${PROGNAME}" | cut -d" " -f1 )
	cloned=$( md5sum "${PROGNAME}" | cut -d" " -f1 )

	if [ ! "${cloned}" = "${current}" ]; then
		echo -e "Downloaded install appears to be different, running install"
		make install > /dev/null 2>&1
	else
		echo -e "Current install and downloaded install are the same, skipping"
	fi

	cd ..

	rm -Rf ${PROGNAME}

	popd > /dev/null
}

# Usage
# Parameters : None
function Usage()
{
	echo -e "System Metrics Usage v${sysmetricsver}"
	echo -e "==========================="
	echo -e "-h\t\t\t\tThis menu"
	echo -e "-v\t\t\t\tVersion Info"
	echo -e "-x\t\t\t\tPlace in test mode, which means result printed to console"
	echo -e "-xx\t\t\t\tPlace in diag mode, i.e. Print every action and still submit data"
	echo -e "-nw\t\t\t\tUse 'wait' mode for netcat"
	echo -e "-update\t\t\t\tUpdate install"
	echo -e "-hb [node#]\t\t\tIssue heartbeat metric"
	echo -e "-g [carbon-relay]\t\tSet receiving carbon relay for Graphite monitoring"
	echo -e "-l [loghost]\t\t\tSet log host, localhost for local syslog, DNS/IP for remote"
	echo -e "-u\t\t\t\tGet uptime/load factor (particularly load)"
	echo -e "-m\t\t\t\tGet Memory info"
	echo -e "-p [profile]\t\t\tSet profile to load"
	echo -e "-t [sensor],[divisor],[label]\tSet Temp metric"
	echo -e "-s[sensor],[label]\t\tRead generic sensor without interpretation"
	echo -e "-d [drive spec],[label]\t\tSet drive to monitor"
	echo -e "-pr [program|expr],[cmdlist],[user],[label],[id]\tLook for process"

	DebugMsg "Usage"
}

# CheckApps : Check for 2 required and 3 optional apps, netcat, nc and bc
function CheckApps()
{
	DebugMsg "CheckApps"

	if [ ! "${LOGNAME}" = "root" ]; then
		echo -e "You must be root to run this"
		return
	fi

	bc --version > /dev/null 2>&1

	if [ $? -eq 127 ]; then
		apt-get -y install bc
	fi

	nc > /dev/null 2>&1

	if [ $? -eq 127 ]; then
		apt-get -y install netcat-openbsd
	fi

	# nping or hping3 or traceroute

	nping -c 1 --tcp -p 0 127.0.0.1 > /dev/null 2>&1

	if [ $? -eq 127 ]; then
		apt-get -y install nmap
	fi

	traceroute 127.0.0.1 > /dev/null 2>&1

	if [ $? -eq 127 ]; then
		apt-get -y install inetutils-traceroute
	fi

	TMPF=/tmp/${RANDOM}.tmp
	wget -O ${TMPF} http://www.google.com > /dev/null 2>&1

	if [ $? -eq 127 ]; then
		apt-get -y install wget
	fi

	[ -e ${TMPF} ] && rm ${TMPF}
}

# Delete Temp File
function RemoveTempFile()
{
	DebugMsg "RemoveTempFile"

	[ -e "${TMPFILE}" ] && rm "${TMPFILE}"
}

# SendToGraphite
# Parameters : [metric category] [metric name] [metric value]
function SendToGraphite()
{
	DebugMsg "SendToGraphite"

	nc > /dev/null 2>&1

	if [ $? -lt 127 -a ! "${GRAPHITE}" = "none" ]; then
		FLAGS=""
		DATAPKT="sysmetrics.${HOSTNAME}.${2}.${2} ${3} `date +%s`"

		[ ${DIAGMODE} -gt 0 ] && echo "Submitting : ${DATAPKT}"

		[ ${NETCATWAIT} -gt 0 ] && FLAGS="-w ${NETCATWAIT}"
		echo "${DATAPKT}" | nc ${FLAGS} ${GRAPHITE} ${GRAPHITEPORT}
	else
		logger -p syslog.info -t "sysmetrics" "Attempt to send output to Graphite failed due to netcat not being available on system"
	fi
}

# SubmitMetric
# Parameters : [metric category] [metric name] [metric value]
function SubmitMetric()
{
	DebugMsg "SubmitMetric"

	if [ ! "${LOGHOST}" = "none" ]; then
		mesg="${1} ${2} ${3}"

		case "${LOGHOST}" in
		"local"|"localhost"|"127.0.0.1")
			logger -p syslog.info -t "sysmetrics" "${mesg}" ;;
		"print"|"console")
			echo "${mesg}" ;;
		"none")
			[ 100 -gt 200 ] && echo "noOp" ;;
		*)
			logger -p syslog.info -n "${LOGHOST}" -t "sysmetrics" "${mesg}" ;;
		esac
	fi

	if [ ! "${GRAPHITE}" = "none" ]; then
		SendToGraphite "${1}" "${2}" "${3}"
	fi
}

# Load Profile
# Parameters : [profile file path]
function LoadProfile()
{
	DebugMsg "LoadProfile"

	while read label value value2 value3 value4 value5 value6; do
		case "${label}" in
		"temp"|"temperature")
			[ "${value}" = "" ] && value="${defaultThermalSensor}"
			[ "${value2}" = "" ] && value2=1
			[ "${value3}" = "" ] && value3="unspecified"

			thermalzones[${zoneCount}]="${value},${value2},${value3}"
			zoneCount=$(( ${zoneCount} + 1 )) ;;
		"sensor")
			[ "${value2}" = "" ] && value2="unspecified"
			sensors[${sensorCount}]="${value},${value2}"
			sensorCount=$(( ${sensorCount} + 1 )) ;;
		"drive")
			[ "${value2}" = "" ] && value2=$(basename ${value})
			drives[${driveCount}]="${value},${value2}"
			driveCount=$(( ${driveCount} + 1 )) ;;
		"process")
			processes[${processCount}]="${value},${value2},${value3},${value4},${value5}"
			processCount=$(( ${processCount} + 1 )) ;;
		"graphite")
			GRAPHITE="${value}"
			[ ! "${value2}" = "" ] && GRAPHITEPORT="${value2}"
			;;
		"netcatwait")
			NETCATWAIT=${NETCATWAITTIMEOUT}
			[ ! "${value2}" = "" ] && NETCATWAIT=${value2}
			;;
		"loghost")
			LOGHOST="${value}" ;;
		"meminfo")
			MEMINFO=1 ;;
		"uptime")
			UPTIME=1 ;;
		"heartbeat")
			HEARTBEAT="${value}" ;;
		"ping")
			# lbl host port
			pinghosts[${pinghostsCount}]="${value},${value2},${value3}"
			pinghostsCount=$(( ${pinghostsCount} + 1 )) ;;
		"traceroute")
			# lbl host
			traceroutes[${traceroutesCount}]="${value},${value2}"
			traceroutesCount=$(( ${traceroutesCount} + 1  )) ;;
		"service")
			# lbl service url sum present-value
			services[${servicesCount}]="${value},${value2},${value3},${value4},${value5}"
			servicesCount=$(( ${servicesCount} + 1 )) ;;
		esac
	done < "${1}"
}

# Heartbeat : Submit a selected non-zero node value to indicate host/sysmetric are still working
# Parameters : [node #]
function Heartbeat()
{
	DebugMode "Entering HeartBeat"

	SubmitMetric "heartbeat" "node" "${1}"
}

# CheckProcesses :  Check for a process, if visible in the process table
# Parameters : None, uses processes array
function CheckProcesses()
{
	DebugMsg "Entering CheckProcesses"

	for ((index=0; index < ${#processes[@]}; ++index)); do
		IFS="," read -r operation pname puser plabel pvalue <<< "${processes[${index}]}"

		presentValue=0

		if [ "${operation}" = "program" ]; then
			if [ "${puser}" = "any" -o "${puser}" = "all" -o "${puser}" = "*" ]; then
				ps --no-headers -C "${pname}" > ${TMPFILE} 2>&1
				[ $? -eq 0 ] && presentValue="${pvalue}"
			else
				ps --no-headers -C "${pname}" -o user= | grep "${puser}" > ${TMPFILE} 2>&1
				[ $? -eq 0 ] && presentValue="${pvalue}"
			fi
		else
			if [ "${puser}" = "any" -o "${puser}" = "all" -o "${puser}" = "*" ]; then
				ps --no-headers -ef | egrep "${pname}" > ${TMPFILE} 2>&1
				[ $? -eq 0 ] && presentValue="${pvalue}"
			else
				ps --no-headers -ef | egrep "${pname}" | grep "${puser}" > ${TMPFILE} 2>&1
				[ $? -eq 0 ] && presentValue="${pvalue}"
			fi
		fi

		count=$(wc -l ${TMPFILE} | cut -d" " -f1)

		SubmitMetric "process" "${plabel}.present" "${presentValue}"
		SubmitMetric "process" "${plabel}.instances" "${count}"

		RemoveTempFile
	done
}

# Read Temperature Sensors
# Parameters : thermalzones Array
function ReadTempSensors()
{
	DebugMsg "ReadTempSensors"

	for ((index=0; index < ${#thermalzones[@]}; ++index)); do
		zone="${thermalzones[${index}]}"
		sensor=$(echo "${zone}" | cut -d"," -f1)
		divisor=$(echo "${zone}" | cut -d"," -f2)
		label=$(echo "${zone}" | cut -d"," -f3)

		case "${sensor}" in
		"vcgencmd")	temperature=$(vcgencmd measure_temp | cut -d"=" -f2 | cut -d"'" -f1) ;;
		*)		temperature=$(cat ${sensor})
				[ ! ${divisor} = "1" ] && temperature=$(echo "${temperature}/${divisor}" | bc -l) ;;
		esac

		SubmitMetric "temperature" "${label}" "${temperature}"
	done
}

# Read Generic Sensors : Read generic sensors without interpretation (Temp, Fan Speed, chassis alarm, etc...)
# Parameters : Sensors array
function ReadSensors()
{
	DebugMsg "ReadSensors"

	for ((index=0; index < ${#sensors[@]}; ++index)); do
		sensor="${sensors[${index}]}"
		sensorPath=$(echo "${sensor}" | cut -d"," -f1)
		label=$(echo "${sensor}" | cut -d"," -f2)
		value=$(cat "${sensorPath}")
		SubmitMetric "sensor" "${label}" "${value}"
	done
}

# Get Drive Usage
# Parameters : None
function GetDrives()
{
	DebugMsg "GetDrives"

	local -a drvs
	local -a lbls

	for ((index=0; index < ${#drives[@]}; ++index)); do
		drv=$(echo "${drives[${index}]}" | cut -d"," -f1)
		lbl=$(echo "${drives[${index}]}" | cut -d"," -f2)

		drvs[${index}]=$(df -BM "${drv}" | tail -n +2)
		lbls[${index}]="${lbl}"
	done

	for ((index=0; index < ${#drvs[@]}; ++index)); do
		IFS=" " read -r drive size used available percent mounted rem <<< "${drvs[${index}]}"
		lbl=${lbls[${index}]}

		SubmitMetric "drive.space.used" "${lbl}" "${used%%M}"
		SubmitMetric "drive.space.available" "${lbl}" "${available%%M}"
		SubmitMetric "drive.space.percentused" "${lbl}" "${percent%%%}"
	done
}

# GetMemInfo
# Paremeters : None
function GetMemInfo()
{
	DebugMsg "GetMemInfo"

	total=$(cat /proc/meminfo | grep "MemTotal" | tr -s " " | cut -d" " -f2)
	free=$(cat /proc/meminfo | grep "MemFree" | tr -s " " | cut -d" " -f2)
	available=$(cat /proc/meminfo | grep "MemAvailable" | tr -s " " | cut -d" " -f2)
	SubmitMetric "memory" "total" "${total}"
	SubmitMetric "memory" "free" "${free}"
	SubmitMetric "memory" "available" "${available}"
}

# GetUptimeInfo
# Parameters: None
function GetUptimeInfo()
{
	DebugMsg "GetUptimeInfo"

	output="$(uptime)"

	IFS=" " read -r field1 field2 field3 field4 field5 field6 field7 field8 field9 field10 field11 field12 field13 <<< "${output}"

	if [ "${field4}" = "min," ]; then
		# time up 2 min, 2 users, load average: 2.45, 2.40, 0.01
		mins="${field3}"
		loadfactor="${field9%%,*}"
		users="${field5}"
		dec=$(echo "${mins} / 60" | bc -l)
		dec=$(echo "${dec} / 24" | bc -l)
		days="${dec}"
	elif [ "${field4}" = "days," ]; then
		# time up 5 days, 6 min, 1 user, load average: 2.45, 2.40, 0.01
		# time up 5 days, 3:11, 1 user, load average: 1.0, 1.0, 1.0

		if [ "${field6}" = "min," ]; then
			mins="${field5}"
			hrs=0
			loadfactor="${field11%%,*}"
			users="${field7}"
		else
			field5="${field5%%,*}"
			mins="${field5##*:}"
			hrs="${field5%%:*}"
			loadfactor="${field10%%,*}"
			users="${field6}"
		fi

		dec=$(echo "${mins} / 60" | bc -l)
		dec=$(echo "${dec} + ${hrs}" | bc -l)
		dec=$(echo "${dec} / 24" | bc -l)
		days=$(echo "${field3} + ${dec}" | bc -l)
	elif [ "${field4}" = "day," ]; then
		# time up 1 day, x min, 1 user, load average: 1.0, 1.0, 1.0
		# time up 1 day, 3:y, 1 user load average: 1.0, 1.0, 1.0
		# Day and some hours/minutes

		if [ "${field6}" = "min," ]; then
			mins="${field5}"
			hrs=0
			loadfactor="${field11%%,*}"
			users="${field7}"
		else
			field5="${field5%%,*}"
			mins="${field5##*:}"
			hrs="${field5%%:*}"
			loadfactor="${field10%%,*}"
			users="${field6}"
		fi

		dec=$(echo "${mins} / 60" | bc -l)
		dec=$(echo "${dec} + ${hrs}" | bc -l)
		dec=$(echo "${dec} / 24" | bc -l)
		days=$(echo "${field3} + ${dec}" | bc -l)
	elif [ "${field5}" = "users," -o "${field5}" = "user," ]; then
		# time up 3:11, 1 users, load average: 2.45, 2.40, 0.01
		field3="${field3%%,*}"
		mins="${field3##*:}"
		hrs="${field3%%:*}"
		dec=$(echo "${mins} / 60" | bc -l)
		dec=$(echo "${dec} + ${hrs}" | bc -l)
		days=$(echo "${dec} / 24" | bc -l)
		loadfactor="${field8%%,*}"
		users="${field4}"
	fi

	SubmitMetric "uptime" "uptime" "${days}"
	SubmitMetric "uptime" "users" "${users}"
	SubmitMetric "uptime" "load" "${loadfactor}"
}

# Get Ping Hosts :
# Parameters : none
function GetPingHosts()
{
	DebugMsg "GetPingHosts"

	for ((index=0; index < ${#pinghosts[@]}; ++index)); do
		IFS="," read -r lbl host port <<< "${pinghosts[${index}]}"
		if [ ! "${port}" = "" ]; then
			${PORTPING} -c ${PINGCOUNT} --tcp -p "${port}" "${host}" | egrep "Max rtt|RCVD" > "${TMPFILE}"
			grep "Max rtt" "${TMPFILE}" > "${TMPFILE}.max"
			grep "RCVD" "${TMPFILE}" | tail -n 1 > "${TMPFILE}.rcvd"
			IFS=" " read -r f1 f2 f3 f4 f5 f6 flag f8 <<< $( cat "${TMPFILE}.rcvd" )
			IFS=" " read -r v1 v2 max s1 v3 v4 min s2 v5 v6 avgup <<< $( cat "${TMPFILE}.max" )

			avg=$( echo "${avgup%%ms} / 1000" | bc -l )

			[ -e "${TMPFILE}.max" ] && rm "${TMPFILE}.max"
			[ -e "${TMPFILE}.rcvd" ] && rm "${TMPFILE}.rcvd"
			[ -e "${TMPFILE}.avgup" ] && rm "${TMPFILE}.avgup"

			[ "${avg}" = "N/A" ] && avg=0
			[ "${flag}" = "RA" ] && avg=0

			SubmitMetric "ping" "${lbl}" "${avg}"
		else
			ping -q -c ${PINGCOUNT} "${host}" | egrep "rtt" > "${TMPFILE}"
			IFS=" " read -r line msg eql values tm <<< $( cat "${TMPFILE}" )
			echo "${values}" > "${TMPFILE}"

			while IFS="/" read -r min avg max mdev; do
				SubmitMetric "ping" "${lbl}" "${avg}"
			done < "${TMPFILE}"
		fi
	done

	RemoveTempFile
}

# Get Traceroutes :
# Parameters : none
function GetTraceroutes()
{
	DebugMsg "GetTraceroutes"

	for ((index=0; index < ${#traceroutes[@]}; ++index)); do
		IFS="," read -r lbl host <<< "${traceroutes[${index}]}"

		pathlength=$(traceroute "${host}" | egrep -v "traceroute" | wc -l )

		SubmitMetric "traceroute" "${lbl}" "${pathlength}"
	done
}

# Get Services :
# Parameters : none
function GetServices()
{
	DebugMsg "GetServices"

	for ((index=0; index < ${#services[@]}; ++index)); do
		IFS="," read -r lbl service url sum presentvalue  <<< "${services[${index}]}"

		FILESIZE=0
		STATE=0

		case ${service} in
		"http"|"https")
			wget -O "${TMPFILE}" "${url}" > /dev/null 2>&1
			[ $? -ne 0 ] && STATE=1
			FILESIZE=$(stat -c%s "${TMPFILE}")
			;;
		esac

		SubmitMetric "service" "${lbl}_state" "${STATE}"
		SubmitMetric "service" "${lbl}_size" "${FILESIZE}"

		if [ ! "${sum}" = "" -a -e "${TMPFILE}" ]; then
			mdFivesum=$(md5sum "${TMPFILE}" | cut -d" " -f1)

			if [ ! "${mdFivesum}" = "${sum}" ]; then
				SubmitMetric "service" "${lbl}_sum" "${presentvalue}"
			fi
		fi
	done

	RemoveTempFile
}

#
# Main Loop
#

sysmetricsver="${MAJORVER}.${MINORVER}"
export sysmetricsver

DebugMsg "Entering Main Loop - Parsing Args"

while [ ! "${1}" = "" ]; do
	case "${1}" in
	"-h")	Usage
		exit 1 ;;
	"-update")
		UpdateMe
		exit 1 ;;
	"-v"|"--version")
		MyVersion
		exit 1 ;;
	"-x")	DEBUGMODE=1
		DIAGMODE=0 ;;
	"-xx")	DIAGMODE=1
		DEBUGMODE=1 ;;
	"-nw")	NETCATWAIT=1 ;;
	"-hb")	HEARTBEAT="${2}"
		shift 1 ;;
	"-g")	GRAPHITE="${2}"
		shift 1 ;;
	"-l")	LOGHOST="${2}"
		shift 1 ;;
	"-u")	UPTIME=1 ;;
	"-m")	MEMINFO=1 ;;
	"-p")	PROFILE="${2}"
		shift 1 ;;
	"-pr")	processes[${processCount}]="${2}"
		processCount=$(( ${processCount} + 1 ))
		shift 1 ;;
	"-s")	sensors[${sensorCount}]="${2}"
		sensorCount=$(( ${sensorCount} + 1))
		shift 1 ;;
	"-t")	thermalzones[${zoneCount}]="${2}"
		zoneCount=$(( ${zoneCount} + 1 ))
		shift 1 ;;
	"-d")	drives[${driveCount}]="${2}"
		driveCount=$(( ${driveCount} + 1 ))
		shift 1 ;;
	"-xa")
		CheckApps
		exit 1 ;;
	*)	excessargs[${excessargsCount}]="${1}"
		excessargsCount=$(( ${excessargsCount} + 1 )) ;;
	esac

	shift 1
done

if [ ! "${PROFILE}" = "none" ]; then
	LoadProfile "${PROFILE}"
elif [ ${excessargsCount} -gt 0 ]; then
	# Quick fix for missing "-p" cla-flag
	for ((index=0; index < ${#excessargs[@]}; ++index)); do
		[ -f "${excessargs[${index}]}" ] && LoadProfile "${excessargs[${index}]}"
	done
fi

# Debug Mode is basically a simulation with a step by step printout of what the script is doing, no values are submitted
# Diag Mode is Debug Mode, but values are still submitted
if [ ${DEBUGMODE} -gt 0 ]; then
	DebugMsg "Forcing DebugMode"

	LOGHOST=print
	if [ ${DIAGMODE} -eq 0 ]; then
		GRAPHITE=none
	else
		DebugMsg "Forcing DiagMode - Values Will Be Submitted"
	fi
fi

[ ${#thermalzones[@]} -gt 0 ] &&  ReadTempSensors
[ ${#sensors[@]} -gt 0 ] && ReadSensors
[ ${#drives[@]} -gt 0 ] && GetDrives
[ ${MEMINFO} -gt 0 ] && GetMemInfo
[ ${UPTIME} -gt 0 ] && GetUptimeInfo
[ ! ${HEARTBEAT} = "none" ] && Heartbeat "${HEARTBEAT}"
[ ${#processes[@]} -gt 0 ] && CheckProcesses
[ ${#pinghosts[@]} -gt 0 ] && GetPingHosts
[ ${#traceroutes[@]} -gt 0 ] && GetTraceroutes
[ ${#services[@]} -gt 0 ] && GetServices

[ ${DEBUGMODE} -gt 0 ] && DebugMsg "Exitting Main Loop"
