#!/bin/bash

MAJORVER=0
MINORVER=1

DEBUGMODE=0
DIAGMODE=0

declare -a drives
declare -a thermalzones
declare -a sensors

driveCount=0
zoneCount=0
sensorCount=0

defaultThermalSensor="/sys/class/thermal/thermal_zone0/temp,1000"

temperature=""

TMPFILE="/tmp/sysmetric.tmp.${RANDOM}"
PROFILE="none"
LOGHOST="none"
GRAPHITE="none"
MEMINFO=0
UPTIME=0

# DebugMsg : Print Debug messages
# Parameters : [mesg]
function DebugMsg()
{
	[ ${DIAGMODE} -gt 0 ] && echo -e "Debug : ${1}"
}

# Usage
# Parameters : None
function Usage()
{
	echo -e "System Metrics Usage v${MAJORVER}.${MINORVER}"
	echo -e "==========================="
	echo -e "-h\t\t\t\tThis menu"
	echo -e "-v\t\t\t\tVersion Info"
	echo -e "-x\t\t\t\tPlace in test mode, which means result printed to console"
	echo -e "-g [carbon-relay]\t\tSet receiving carbon relay for Graphite monitoring"
	echo -e "-l [loghost]\t\t\tSet log host, localhost for local syslog, DNS/IP for remote"
	echo -e "-u\t\t\t\tGet uptime/load factor (particularly load)"
	echo -e "-m\t\t\t\tGet Memory info"
	echo -e "-p [profile]\t\t\tSet profile to load"
	echo -e "-t [sensor],[divisor],[label]\tSet Temp metric"
	echo -e "-s [sensor],[label]\t\tRead generic sensor without interpretation"
	echo -e "-d [drive spec],[label]\t\tSet drive to monitor"

	[ ${DEBUGMODE} -gt 0 ] && DebugMsg "Usage"
}

# CheckApps : Check for 2 required apps, "netcat/nc" and "bc"
function CheckApps()
{
	[ ${DEBUGMODE} -gt 0 ] && DebugMsg "CheckApps"

	if [ ! "${LOGNAME}" = "root" ]; then
		echo -e "You must be root to run this"
		return
	fi

	bc --version > /dev/null 2>&1

	if [ $? -eq 127 ]; then
		apt-get -y install bc
	fi

	nc > /dev/null 2>&1

	if [ $? -eq 127 ]; then
		apt-get -y install netcat-openbsd
	fi
}

# Delete Temp File
function RemoveTempFile()
{
	[ ${DEBUGMODE} -gt 0 ] && DebugMsg "RemoveTempFile"

	[ -e "${TMPFILE}" ] && rm "${TMPFILE}"
}

# SendToGraphite
# Parameters : [metric category] [metric name] [metric value]
function SendToGraphite()
{
	[ ${DEBUGMODE} -gt 0 ] && DebugMsg "SendToGraphite"

	nc > /dev/null 2>&1

	if [ $? -lt 127 -a ! "${GRAPHITE}" = "none" ]; then
		echo "sysmetrics.${HOSTNAME}.${1}.${2} ${3} `date +%s`" | nc ${GRAPHITE} 2003
	else
		logger -p syslog.info -t "sysmetrics" "Attempt to send output to Graphite failed due to netcat not being available on system"
	fi
}

# SubmitMetric
# Parameters : [metric category] [metric name] [metric value]
function SubmitMetric()
{
	[ ${DEBUGMODE} -gt 0 ] && DebugMsg "SubmitMetric"

	if [ ! "${LOGHOST}" = "none" ]; then
		mesg="${1} ${2} ${3}"

		case "${LOGHOST}" in
		"local"|"localhost"|"127.0.0.1")
			logger -p syslog.info -t "sysmetrics" "${mesg}" ;;
		"print"|"console")
			echo "${mesg}" ;;
		"none")
			[ 100 -gt 200 ] && echo "noOp" ;;
		*)
			logger -p syslog.info -n "${LOGHOST}" -t "sysmetrics" "${mesg}" ;;
		esac
	fi

	if [ ! "${GRAPHITE}" = "none" ]; then
		SendToGraphite "${1}" "${2}" "${3}"
	fi
}

# Load Profile
# Parameters : [profile file path]
function LoadProfile()
{
	[ ${DEBUGMODE} -gt 0 ] && DebugMsg "LoadProfile"

	while read label value value2 value3; do
		case "${label}" in
		"temp"|"temperature")
			[ "${value}" = "" ] && value="${defaultThermalSensor}"
			[ "${value2}" = "" ] && value2=1
			[ "${value3}" = "" ] && value3="unspecified"

			thermalzones[${zoneCount}]="${value},${value2},${value3}"
			zoneCount=$(( ${zoneCount} + 1 )) ;;
		"sensor")
			[ "${value2}" = "" ] && value2="unspecified"
			sensors[${sensorCount}]="${value},${value2}"
			sensorCount=$(( ${sensorCount} + 1 )) ;;
		"drive")
			[ "${value2}" = "" ] && value2=$(basename ${value})
			drives[${driveCount}]="${value},${value2}"
			driveCount=$(( ${driveCount} + 1 )) ;;
		"graphite")
			GRAPHITE="${value}" ;;
		"loghost")
			LOGHOST="${value}" ;;
		"meminfo")
			MEMINFO=1 ;;
		"uptime")
			UPTIME=1 ;;
		esac
	done < "${1}"
}

# Read Temperature Sensors
# Parameters : thermalzones Array
function ReadTempSensors()
{
	[ ${DEBUGMODE} -gt 0 ] && DebugMsg "ReadTempSensors"

	for ((index=0; index < ${#thermalzones[@]}; ++index)); do
		zone="${thermalzones[${index}]}"
		sensor=$(echo "${zone}" | cut -d"," -f1)
		divisor=$(echo "${zone}" | cut -d"," -f2)
		label=$(echo "${zone}" | cut -d"," -f3)

		case "${sensor}" in
		"vcgencmd")	temperature=$(vcgencmd measure_temp | cut -d"=" -f2 | cut -d"'" -f1) ;;
		*)		temperature=$(cat ${sensor})
				[ ! ${divisor} = "1" ] && temperature=$(echo "${temperature}/${divisor}" | bc -l) ;;
		esac

		SubmitMetric "temperature" "${label}" "${temperature}"
	done
}

# Read Generic Sensors : Read generic sensors without interpretation (Temp, Fan Speed, chassis alarm, etc...)
# Parameters : Sensors array
function ReadSensors()
{
	[ ${DEBUGMODE} -gt 0 ] && DebugMsg "ReadSensors"

	for ((index=0; index < ${#sensors[@]}; ++index)); do
		sensor="${sensors[${index}]}"
		sensorPath=$(echo "${sensor}" | cut -d"," -f1)
		label=$(echo "${sensor}" | cut -d"," -f2)
		value=$(cat "${sensorPath}")
		SubmitMetric "sensor" "${label}" "${value}"
	done
}

# Get Drive Usage
# Parameters : None
function GetDrives()
{
	[ ${DEBUGMODE} -gt 0 ] && DebugMsg "GetDrives"

	local -a drvs
	local -a lbls

	for ((index=0; index < ${#drives[@]}; ++index)); do
		drv=$(echo "${drives[${index}]}" | cut -d"," -f1)
		lbl=$(echo "${drives[${index}]}" | cut -d"," -f2)

		drvs[${index}]=$(df -BM "${drv}" | tail -n +2)
		lbls[${index}]="${lbl}"
	done

	for ((index=0; index < ${#drvs[@]}; ++index)); do
		IFS=" " read -r drive size used available percent mounted rem <<< "${drvs[${index}]}"
		lbl=${lbls[${index}]}

		SubmitMetric "drive.space.used" "${lbl}" "${used%%M}"
		SubmitMetric "drive.space.available" "${lbl}" "${available%%M}"
		SubmitMetric "drive.space.percentused" "${lbl}" "${percent%%%}"
	done
}

# GetMemInfo
# Paremeters : None
function GetMemInfo()
{
	[ ${DEBUGMODE} -gt 0 ] && DebugMsg "GetMemInfo"

	total=$(cat /proc/meminfo | grep "MemTotal" | tr -s " " | cut -d" " -f2)
	free=$(cat /proc/meminfo | grep "MemFree" | tr -s " " | cut -d" " -f2)
	available=$(cat /proc/meminfo | grep "MemAvailable" | tr -s " " | cut -d" " -f2)
	SubmitMetric "memory" "total" "${total}"
	SubmitMetric "memory" "free" "${free}"
	SubmitMetric "memory" "available" "${available}"
}

# GetUptimeInfo
# Parameters: None
function GetUptimeInfo()
{
	[ ${DEBUGMODE} -gt 0 ] && DebugMsg "GetUptimeInfo"

	output="$(uptime)"

	IFS=" " read -r field1 field2 field3 field4 field5 field6 field7 field8 field10 field11 field12 field13 <<< "${output}"

	if [ "${field4}" = "min," ]; then
		# time up 2 min, 2 users, load average: 2.45, 2.40, 0.01
		mins="${field3}"
		loadfactor="${field9%%,*}"
		users="${field5}"
		dec=$(echo "${mins} / 60" | bc -l)
		dec=$(echo "${dec} / 24" | bc -l)
		days="${dec}"
	elif [ "${field4}" = "days," ]; then
		# time up 5 days, 6 min, 1 user, load average: 2.45, 2.40, 0.01
		# time up 5 days, 3:11, 1 user, load average: 1.0, 1.0, 1.0

		if [ "${field6}" = "min," ]; then
			mins="${field5}"
			hrs=0
			loadfactor="${field11%%,*}"
			users="${field7}"
		else
			field5="${field5%%,*}"
			mins="${field5##*:}"
			hrs="${field5%%:*}"
			users="${field6}"
		fi

		dec=$(echo "${mins} / 60" | bc -l)
		dec=$(echo "${dec} + ${hrs}" | bc -l)
		dec=$(echo "${dec} / 24" | bc -l)
		days=$(echo "${field3} + ${dec}" | bc -l)
	elif [ "${field4}" = "day," ]; then
		# time up 1 day, x min, 1 user, load average: 1.0, 1.0, 1.0
		# time up 1 day, 3:y, 1 user load average: 1.0, 1.0, 1.0
		# Day and some hours/minutes

		if [ "${field6}" = "min," ]; then
			mins="${field5}"
			hrs=0
			loadfactor="${field11%%,*}"
			users="${field7}"
		else
			field5="${field5%%,*}"
			mins="${field5##*:}"
			hrs="${field5%%:*}"
			loadfactor="${field10%%,*}"
			users="${field6}"
		fi

		dec=$(echo "${mins} / 60" | bc -l)
		dec=$(echo "${dec} + ${hrs}" | bc -l)
		dec=$(echo "${dec} / 24" | bc -l)
		days=$(echo "${field3} + ${dec}" | bc -l)
	elif [ "${field5}" = "users," ]; then
		# time up 3:11, 1 users, load average: 2.45, 2.40, 0.01
		field3="${field3%%,*}"
		mins="${field3##*:}"
		hrs="${field3%%:*}"
		dec=$(echo "${mins} / 60" | bc -l)
		dec=$(echo "${dec} + ${hrs}" | bc -l)
		days=$(echo "${dec} / 24" | bc -l)
		loadfactor="${field8%%,*}"
		users="${field4}"
	fi

	SubmitMetric "uptime" "uptime" "${days}"
	SubmitMetric "uptime" "users" "${users}"
	SubmitMetric "uptime" "load" "${loadfactor}"
}

#
# Main Loop
#

[ ${DEBUGMODE} -gt 0 ] && DebugMsg "Entering Main Loop - Parsing Args"

while [ ! "${1}" = "" ]; do
	case "${1}" in
	"-h")	Usage
		exit 1 ;;
	"-v"|"--version")
		echo -e "Version ${MAJORVER}.${MINORVER}"
		exit 1 ;;
	"-x")	DEBUGMODE=1 ;;
	"-g")	GRAPHITE="${2}"
		shift 1 ;;
	"-l")	LOGHOST="${2}"
		shift 1 ;;
	"-u")	UPTIME=1 ;;
	"-m")	MEMINFO=1 ;;
	"-p")	PROFILE="${2}"
		shift 1 ;;
	"-s")	sensors[${sensorCount}]="${2}"
		sensorCount=$(( ${sensorCount} + 1))
		shift 1 ;;
	"-t")	thermalzones[${zoneCount}]="${2}"
		zoneCount=$(( ${zoneCount} + 1 ))
		shift 1 ;;
	"-d")	drives[${driveCount}]="${2}"
		driveCount=$(( ${driveCount} + 1 ))
		shift 1 ;;
	"-xa")
		CheckApps
		exit 1 ;;
	esac

	shift 1
done

if [ ! "${PROFILE}" = "none" ]; then
	LoadProfile "${PROFILE}"
fi

if [ ${DEBUGMODE} -gt 0 ]; then
	[ ${DEBUGMODE} -gt 0 ] && DebugMsg "Forcing DebugMode"

	LOGHOST=print
	GRAPHITE=none
fi

[ ${#thermalzones[@]} -gt 0 ] &&  ReadTempSensors
[ ${#sensors[@]} -gt 0 ] && ReadSensors
[ ${#drives[@]} -gt 0 ] && GetDrives
[ ${MEMINFO} -gt 0 ] && GetMemInfo
[ ${UPTIME} -gt 0 ] && GetUptimeInfo

[ ${DEBUGMODE} -gt 0 ] && DebugMsg "Exitting Main Loop"
